// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhiJD-0mffBXV-AJ9EwusPzj-fNNGRYII',
    appId: '1:744633819126:web:0c2b3da2eb25cb2644f1d7',
    messagingSenderId: '744633819126',
    projectId: 'keyboard-arena',
    authDomain: 'keyboard-arena.firebaseapp.com',
    storageBucket: 'keyboard-arena.firebasestorage.app',
    measurementId: 'G-EKXZMCCLPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCux6Bg-WfAz7xAc29fN1r33UnOYU1M0qI',
    appId: '1:744633819126:android:a4a618648a474f3e44f1d7',
    messagingSenderId: '744633819126',
    projectId: 'keyboard-arena',
    storageBucket: 'keyboard-arena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvI5826GSi4y-onXqcZTd0PqjRR4e2ilY',
    appId: '1:744633819126:ios:50eced8a9516ed9c44f1d7',
    messagingSenderId: '744633819126',
    projectId: 'keyboard-arena',
    storageBucket: 'keyboard-arena.firebasestorage.app',
    androidClientId: '744633819126-nalmgqm3urc46lir13561s5iltl6t7kt.apps.googleusercontent.com',
    iosClientId: '744633819126-mb66hth0ogh9abjds94rc3hg1rqcocr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvI5826GSi4y-onXqcZTd0PqjRR4e2ilY',
    appId: '1:744633819126:ios:50eced8a9516ed9c44f1d7',
    messagingSenderId: '744633819126',
    projectId: 'keyboard-arena',
    storageBucket: 'keyboard-arena.firebasestorage.app',
    androidClientId: '744633819126-nalmgqm3urc46lir13561s5iltl6t7kt.apps.googleusercontent.com',
    iosClientId: '744633819126-mb66hth0ogh9abjds94rc3hg1rqcocr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhiJD-0mffBXV-AJ9EwusPzj-fNNGRYII',
    appId: '1:744633819126:web:9b2908cc37b665ed44f1d7',
    messagingSenderId: '744633819126',
    projectId: 'keyboard-arena',
    authDomain: 'keyboard-arena.firebaseapp.com',
    storageBucket: 'keyboard-arena.firebasestorage.app',
    measurementId: 'G-RPC6ZFLQX2',
  );

}